
# Loads default set of integrations. Do not remove.
default_config:

# HTTP configuration to allow access from traefik
http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - <TRAEFIK_NETWORK>

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
